"""add plan_data table

Revision ID: 7f315f7a67ae
Revises: b7c8d9e0f1a2
Create Date: 2026-04-20 11:33:19.187339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f315f7a67ae'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('activity_code', sa.String(length=50), nullable=False),
    sa.Column('chainage_from', sa.Float(), nullable=False),
    sa.Column('chainage_to', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('planned_qty_lm', sa.Float(), nullable=False),
    sa.Column('target_start', sa.Date(), nullable=False),
    sa.Column('target_end', sa.Date(), nullable=False),
    sa.Column('contractor_name', sa.String(length=200), nullable=False),
    sa.Column('road_side', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Note: gps_waypoints drop is skipped as it may not exist in all environments
    op.alter_column('site_data_transactions', 'gps_accuracy_m',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_data_transactions', 'gps_accuracy_m',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.create_table('gps_waypoints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('engineer_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('lat', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=False),
    sa.Column('lng', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=False),
    sa.Column('accuracy_m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('captured_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('gps_waypoints_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gps_waypoints_pkey'))
    )
    op.drop_table('plan_data')
    # ### end Alembic commands ###
